### ISSUE TITLE
Kindly Requesting Access to Your Code for Learning Purposes

### ISSUE THREAD

**Issue by TinaLin1215** [jayangcs/SketchSeger#1]
Hi~~
I hope this message finds you well. I came across your work while exploring the realm of sketch segment, and I was deeply impressed by your contributions and expertise. Your insights and solutions have sparked my curiosity, and I would love to delve deeper into how you've approached the challenges faced in your work. I noticed that the source code for your project isn't currently available on GitHub or any other public platform. I understand that sharing code can involve various considerations, and I fully respect your decision to keep it private if necessary. However, I would be extremely grateful if you could consider allowing me access to it for learning purposes.
Thank you for taking the time to read my request.

**Comment by jayangcs** [comment]
Hello! Thank you for your appreciation of our work, we have now released the code, come and give it a try!
